development:
  stripe_secret_key: 'sk_test_aw4XssbQVLBfO2CPdkVhyd8B'
  stripe_publishable_key: 'pk_test_42SjUmF3xTfYRgd1Q4rDWL6mnqgqu0jnFA7ivEJHtKE35dhy8UKYNJD4n6Fqji9LrA7znzhLnjNLhTwy9E2nqdZ1C00YVdVYnNV'
  website_domain: http://localhost:3000

production:
  stripe_secret_key: ''
  stripe_publishable_key: ''
  website_domain: ''
